return {
	--    "nvim-telescope/telescope.nvim",
	--    dependencies = { "nvim-lua/plenary.nvim",
	--        "nvim-tree/nvim-web-devicons",
	--    },
	--    config = function()
	--        require("telescope").setup({
	--            defaults = {
	--                prompt_prefix = "🔍 ",
	--                selection_caret = "➤ ",
	--                path_display = { "truncate" },
	--            },
	--            pickers = {
	--                find_files = {
	--                    hidden = true, -- Show hidden files
	--                },
	--                live_grep = {
	--                    additional_args = function()
	--                        return { "--hidden" }
	--                    end,
	--                },
	--            },
	--        })
	-- local builtin = require('telescope.builtin')
	--        vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
	--        vim.keymap.set('n', '<C-p>', builtin.git_files, {})
	--        vim.keymap.set('n', '<leader>pws', function()
	--            local word = vim.fn.expand("<cword>")
	--            builtin.grep_string({ search = word })
	--        end)
	--        vim.keymap.set('n', '<leader>pWs', function()
	--            local word = vim.fn.expand("<cWORD>")
	--            builtin.grep_string({ search = word })
	--        end)
	--        vim.keymap.set('n', '<leader>ps', function()
	--            builtin.grep_string({ search = vim.fn.input("Grep > ") })
	--        end)
	--        vim.keymap.set('n', '<leader>vh', builtin.help_tags, {})
	--
	--
	--    end,
}


